name: Deploy to GitHub Pages

on:
  # Se ejecutará cada vez que hagas push a la rama main
  push:
    branches: ["main"]
  # Permite ejecutar el flujo manualmente desde la pestaña Actions
  workflow_dispatch:

# Otorga los permisos necesarios para modificar GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente a la vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Obtener el código
        uses: actions/checkout@v4
      
      - name: ⚙️ Configurar Pages
        uses: actions/configure-pages@v5
        
      - name: 📦 Subir los archivos estáticos
        uses: actions/upload-pages-artifact@v3
        with:
          # Le indicamos que suba específicamente el contenido de esta carpeta
          path: './docencia-4.0'
          
      - name: 🚀 Desplegar en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
